version: '3.7'

services:
  snipeit_db:
    container_name: snipeit_db
    image: mysql:5.6
    restart: unless-stopped
    env_file: .env
    volumes:
      - "./data:/var/lib/mysql"
    networks:
      - backend

  snipeit:
    container_name: snipeit
    image: snipe/snipe-it:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - snipeit_db
    ports:
      - "80:80"
    networks:
      - backend
      - frontend

networks:
  backend:
    external: false
  frontend:
    external: true
