version: '3.7'

services:
  db:
    container_name: inventory-it_db
    image: mysql:5.6
    restart: unless-stopped
    env_file: .env
    volumes:
      - "./data:/var/lib/mysql"
    networks:
      - backend

  app:
    container_name: inventory-it
    image: snipe/snipe-it:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "10003:80"
    networks:
      - backend
      - frontend

networks:
  backend:
    external: false
  frontend:
    external: true
